package com.abcproduct.domain.model;

import lombok.Data;
import lombok.ToString;

@ToString
@Data
public class Stock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.product_id
     *
     * @mbg.generated Tue Apr 13 15:02:42 JST 2021
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.warehouse_id
     *
     * @mbg.generated Tue Apr 13 15:02:42 JST 2021
     */
    private Integer warehouseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.stock_count
     *
     * @mbg.generated Tue Apr 13 15:02:42 JST 2021
     */
    private Integer stockCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.stock_in
     *
     * @mbg.generated Tue Apr 13 15:02:42 JST 2021
     */
    private Boolean stockIn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.stock_out
     *
     * @mbg.generated Tue Apr 13 15:02:42 JST 2021
     */
    private Boolean stockOut;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.product_id
     *
     * @return the value of stock.product_id
     *
     * @mbg.generated Tue Apr 13 15:02:42 JST 2021
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.product_id
     *
     * @param productId the value for stock.product_id
     *
     * @mbg.generated Tue Apr 13 15:02:42 JST 2021
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.warehouse_id
     *
     * @return the value of stock.warehouse_id
     *
     * @mbg.generated Tue Apr 13 15:02:42 JST 2021
     */
    public Integer getWarehouseId() {
        return warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.warehouse_id
     *
     * @param warehouseId the value for stock.warehouse_id
     *
     * @mbg.generated Tue Apr 13 15:02:42 JST 2021
     */
    public void setWarehouseId(Integer warehouseId) {
        this.warehouseId = warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.stock_count
     *
     * @return the value of stock.stock_count
     *
     * @mbg.generated Tue Apr 13 15:02:42 JST 2021
     */
    public Integer getStockCount() {
        return stockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.stock_count
     *
     * @param stockCount the value for stock.stock_count
     *
     * @mbg.generated Tue Apr 13 15:02:42 JST 2021
     */
    public void setStockCount(Integer stockCount) {
        this.stockCount = stockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.stock_in
     *
     * @return the value of stock.stock_in
     *
     * @mbg.generated Tue Apr 13 15:02:42 JST 2021
     */
    public Boolean getStockIn() {
        return stockIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.stock_in
     *
     * @param stockIn the value for stock.stock_in
     *
     * @mbg.generated Tue Apr 13 15:02:42 JST 2021
     */
    public void setStockIn(Boolean stockIn) {
        this.stockIn = stockIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.stock_out
     *
     * @return the value of stock.stock_out
     *
     * @mbg.generated Tue Apr 13 15:02:42 JST 2021
     */
    public Boolean getStockOut() {
        return stockOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.stock_out
     *
     * @param stockOut the value for stock.stock_out
     *
     * @mbg.generated Tue Apr 13 15:02:42 JST 2021
     */
    public void setStockOut(Boolean stockOut) {
        this.stockOut = stockOut;
    }
}