package com.abcproduct.domain.model;

import lombok.ToString;

@ToString
public class TestItemModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_item.id
	 * @mbg.generated  Fri Apr 02 16:44:45 JST 2021
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_item.item_name
	 * @mbg.generated  Fri Apr 02 16:44:45 JST 2021
	 */
	private String itemName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_item.item_count
	 * @mbg.generated  Fri Apr 02 16:44:45 JST 2021
	 */
	private Integer itemCount;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_item.id
	 * @return  the value of test_item.id
	 * @mbg.generated  Fri Apr 02 16:44:45 JST 2021
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_item.id
	 * @param id  the value for test_item.id
	 * @mbg.generated  Fri Apr 02 16:44:45 JST 2021
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_item.item_name
	 * @return  the value of test_item.item_name
	 * @mbg.generated  Fri Apr 02 16:44:45 JST 2021
	 */
	public String getItemName() {
		return itemName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_item.item_name
	 * @param itemName  the value for test_item.item_name
	 * @mbg.generated  Fri Apr 02 16:44:45 JST 2021
	 */
	public void setItemName(String itemName) {
		this.itemName = itemName == null ? null : itemName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_item.item_count
	 * @return  the value of test_item.item_count
	 * @mbg.generated  Fri Apr 02 16:44:45 JST 2021
	 */
	public Integer getItemCount() {
		return itemCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_item.item_count
	 * @param itemCount  the value for test_item.item_count
	 * @mbg.generated  Fri Apr 02 16:44:45 JST 2021
	 */
	public void setItemCount(Integer itemCount) {
		this.itemCount = itemCount;
	}
}