package com.abcproduct.domain.model;

import lombok.Data;
import lombok.ToString;

@ToString
@Data
public class Warehouse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.warehouse_id
     *
     * @mbg.generated Tue Apr 13 15:02:42 JST 2021
     */
    private Integer warehouseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.warehouse_name
     *
     * @mbg.generated Tue Apr 13 15:02:42 JST 2021
     */
    private String warehouseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.warehouse_address
     *
     * @mbg.generated Tue Apr 13 15:02:42 JST 2021
     */
    private String warehouseAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.warehouse_id
     *
     * @return the value of warehouse.warehouse_id
     *
     * @mbg.generated Tue Apr 13 15:02:42 JST 2021
     */
    public Integer getWarehouseId() {
        return warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.warehouse_id
     *
     * @param warehouseId the value for warehouse.warehouse_id
     *
     * @mbg.generated Tue Apr 13 15:02:42 JST 2021
     */
    public void setWarehouseId(Integer warehouseId) {
        this.warehouseId = warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.warehouse_name
     *
     * @return the value of warehouse.warehouse_name
     *
     * @mbg.generated Tue Apr 13 15:02:42 JST 2021
     */
    public String getWarehouseName() {
        return warehouseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.warehouse_name
     *
     * @param warehouseName the value for warehouse.warehouse_name
     *
     * @mbg.generated Tue Apr 13 15:02:42 JST 2021
     */
    public void setWarehouseName(String warehouseName) {
        this.warehouseName = warehouseName == null ? null : warehouseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.warehouse_address
     *
     * @return the value of warehouse.warehouse_address
     *
     * @mbg.generated Tue Apr 13 15:02:42 JST 2021
     */
    public String getWarehouseAddress() {
        return warehouseAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.warehouse_address
     *
     * @param warehouseAddress the value for warehouse.warehouse_address
     *
     * @mbg.generated Tue Apr 13 15:02:42 JST 2021
     */
    public void setWarehouseAddress(String warehouseAddress) {
        this.warehouseAddress = warehouseAddress == null ? null : warehouseAddress.trim();
    }
}