package com.abcproduct.domain.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.abcproduct.domain.model.Stock;
import com.abcproduct.domain.model.StockExample;
@Repository
@Mapper
public interface StockRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock
	 * @mbg.generated  Fri Apr 16 17:57:02 JST 2021
	 */
	long countByExample(StockExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock
	 * @mbg.generated  Fri Apr 16 17:57:02 JST 2021
	 */
	int deleteByExample(StockExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock
	 * @mbg.generated  Fri Apr 16 17:57:02 JST 2021
	 */
	int insert(Stock record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock
	 * @mbg.generated  Fri Apr 16 17:57:02 JST 2021
	 */
	int insertSelective(Stock record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock
	 * @mbg.generated  Fri Apr 16 17:57:02 JST 2021
	 */
	List<Stock> selectByExample(StockExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock
	 * @mbg.generated  Fri Apr 16 17:57:02 JST 2021
	 */
	int updateByExampleSelective(@Param("record") Stock record, @Param("example") StockExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock
	 * @mbg.generated  Fri Apr 16 17:57:02 JST 2021
	 */
	int updateByExample(@Param("record") Stock record, @Param("example") StockExample example);
}