package com.abcproduct.domain.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.abcproduct.domain.model.TestItemModel;
import com.abcproduct.domain.model.TestItemModelExample;

@Mapper
public interface TestItemRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_item
	 * @mbg.generated  Fri Apr 02 16:44:45 JST 2021
	 */
	long countByExample(TestItemModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_item
	 * @mbg.generated  Fri Apr 02 16:44:45 JST 2021
	 */
	int deleteByExample(TestItemModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_item
	 * @mbg.generated  Fri Apr 02 16:44:45 JST 2021
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_item
	 * @mbg.generated  Fri Apr 02 16:44:45 JST 2021
	 */
	int insert(TestItemModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_item
	 * @mbg.generated  Fri Apr 02 16:44:45 JST 2021
	 */
	int insertSelective(TestItemModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_item
	 * @mbg.generated  Fri Apr 02 16:44:45 JST 2021
	 */
	List<TestItemModel> selectByExample(TestItemModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_item
	 * @mbg.generated  Fri Apr 02 16:44:45 JST 2021
	 */
	TestItemModel selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_item
	 * @mbg.generated  Fri Apr 02 16:44:45 JST 2021
	 */
	int updateByExampleSelective(@Param("record") TestItemModel record, @Param("example") TestItemModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_item
	 * @mbg.generated  Fri Apr 02 16:44:45 JST 2021
	 */
	int updateByExample(@Param("record") TestItemModel record, @Param("example") TestItemModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_item
	 * @mbg.generated  Fri Apr 02 16:44:45 JST 2021
	 */
	int updateByPrimaryKeySelective(TestItemModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_item
	 * @mbg.generated  Fri Apr 02 16:44:45 JST 2021
	 */
	int updateByPrimaryKey(TestItemModel record);

}