package com.abcproduct.domain.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.abcproduct.domain.model.Testitem;
import com.abcproduct.domain.model.TestitemExample;

@Mapper
public interface TestitemRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_item
	 * @mbg.generated  Tue Apr 13 15:02:42 JST 2021
	 */
	long countByExample(TestitemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_item
	 * @mbg.generated  Tue Apr 13 15:02:42 JST 2021
	 */
	int deleteByExample(TestitemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_item
	 * @mbg.generated  Tue Apr 13 15:02:42 JST 2021
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_item
	 * @mbg.generated  Tue Apr 13 15:02:42 JST 2021
	 */
	int insert(Testitem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_item
	 * @mbg.generated  Tue Apr 13 15:02:42 JST 2021
	 */
	int insertSelective(Testitem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_item
	 * @mbg.generated  Tue Apr 13 15:02:42 JST 2021
	 */
	List<Testitem> selectByExample(TestitemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_item
	 * @mbg.generated  Tue Apr 13 15:02:42 JST 2021
	 */
	Testitem selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_item
	 * @mbg.generated  Tue Apr 13 15:02:42 JST 2021
	 */
	int updateByExampleSelective(@Param("record") Testitem record, @Param("example") TestitemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_item
	 * @mbg.generated  Tue Apr 13 15:02:42 JST 2021
	 */
	int updateByExample(@Param("record") Testitem record, @Param("example") TestitemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_item
	 * @mbg.generated  Tue Apr 13 15:02:42 JST 2021
	 */
	int updateByPrimaryKeySelective(Testitem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_item
	 * @mbg.generated  Tue Apr 13 15:02:42 JST 2021
	 */
	int updateByPrimaryKey(Testitem record);
}